version: 2
jobs:
  build:
    docker:
    - image: circleci/node:4.8.2
    steps:
    - checkout
    - run: npm built
  lint:
    docker:
    - image: circleci/node:4.8.2
    steps:
    - checkout
    - run: npm run lint
  test:
    docker:
    - image: circleci/node:4.8.2
    steps:
    - checkout
    - run: npm test
workflows:
  version: 2
  lint_and_test:
    jobs:
    - lint
    - test